wg-peer: Improved version.
Via: https://gist.github.com/colemar/030fe6eef8f01858052dc6c29c8cc022

diff --git a/wg-peer b/wg-peer
--- a/wg-peer
+++ b/wg-peer
@@ -1,34 +1,160 @@
 #!/bin/bash
 
-readonly INTERFACE="wg0"
+readonly CFOLDER=/etc/wireguard/clients
+readonly THISFILE=$(basename $0)
 
-# Generate peer keys
-readonly PRIVATE_KEY=$(wg genkey)
-readonly PUBLIC_KEY=$(echo ${PRIVATE_KEY} | wg pubkey)
-readonly PRESHARED_KEY=$(wg genpsk)
+# =================================================
 
-# Read server key from interface
-readonly SERVER_PUBLIC_KEY=$(wg show ${INTERFACE} public-key)
+main () {
+  # Check for root privileges
+  [[ $USER == root ]] || { echo "Root privileges required. Try: sudo $THISFILE"; return 1; }
 
-# Get next free peer IP (This will break after x.x.x.255)
-readonly PEER_ADDRESS=$(wg show ${INTERFACE} allowed-ips | cut -f 2 | awk -F'[./]' '{print $1"."$2"."$3"."1+$4"/"$5}' | sort -t '.' -k 1,1 -k 2,2 -k 3,3 -k 4,4 -n | tail -n1)
+  # Find Wireguard interface
+  if=$(wg show interfaces)
+  [[ $if =~ $'\n' ]] && { echo "WARNING: multiple Wireguard interfaces detected"; }
+  read -r INTERFACE <<<$if; readonly INTERFACE
+  echo "Using interface $INTERFACE"
 
-# Add peer
-wg set ${INTERFACE} peer ${PUBLIC_KEY} preshared-key <(echo ${PRESHARED_KEY}) allowed-ips ${PEER_ADDRESS}
+  case $1 in
+    a*)
+      add_new_peer
+      ;;
+    s*)
+      show_peer_conf $2
+      return
+      ;;
+    d*)
+      pk=$2
+      check_peer_exists $pk || return 1
+      delete_peer $pk
+      return
+      ;;
+    l*)
+      list_peers
+      return
+      ;;
+    *)
+      usage
+      return
+      ;;
+  esac
+}
 
-# Logging
-echo "Added peer ${PEER_ADDRESS} with public key ${PUBLIC_KEY}"
+# =================================================
 
-# Generate peer config QR code
-cat << END_OF_CONFIG | qrencode -t ANSIUTF8
+usage () {
+cat <<USAGE
+$THISFILE [add|show <peer>|del <peer>|list]
+
+a[dd]  : add a new peer
+s[how] : show peer configuration
+d[el]  : delete peer
+l[ist] : list peers
+<peer> is peer public key as shown by list command
+USAGE
+}
+
+build_peer_list () {
+  PEERLIST=':'$(wg show $INTERFACE peers | awk '{printf $1":"}')
+}
+
+check_peer_exists () {
+  local pk=$1
+  build_peer_list
+  [[ $PEERLIST =~ ":${pk}:" ]] || { echo "Cannot find peer $pk"; return 1; }
+}
+
+show_peer_conf () {
+  local pk=$1
+  check_peer_exists $pk || return 1
+  local clientfile=$CFOLDER/$(md5sum <<<${pk}); clientfile=${clientfile%% *}
+  [[ -r $clientfile ]] || { echo "Cannot read $clientfile"; return 1; }
+  qrencode -t ANSIUTF8 < $clientfile
+  cat $clientfile
+  echo -e "---------\n"
+  wg show $INTERFACE | awk '$0=="peer: '${pk}'"{f=1; print; next} /^peer:/{f=0} f'
+}
+
+delete_peer () {
+  local pk=$1
+  wg set $INTERFACE peer $pk remove && {
+    wg-quick save ${INTERFACE}
+    clientfile=$CFOLDER/$(md5sum <<<${pk}); clientfile=${clientfile%% *}
+    rm -f $clientfile
+    echo "Removed peer $pk"
+  } || { echo "Cannot remove peer $pk"; return 1; }
+}
+
+list_peers () {
+  wg show $INTERFACE |\
+    awk '/^peer:/{
+            f=1
+            print "# '$THISFILE' show '\''"$2"'\''"
+            print "# '$THISFILE' del '\''"$2"'\''"
+            print
+            next
+            }
+          f'
+}
+
+add_new_peer () {
+  # Generate peer keys
+  PRIVATE_KEY=$(wg genkey)
+  PUBLIC_KEY=$(echo ${PRIVATE_KEY} | wg pubkey)
+  PRESHARED_KEY=$(wg genpsk)
+
+  # Read server key from interface
+  SERVER_PUBLIC_KEY=$(wg show ${INTERFACE} public-key)
+
+  # Get next free peer IP (This will break after x.x.x.255)
+  PEER_ADDRESS=$(wg show ${INTERFACE} allowed-ips |\
+    cut -f 2 |\
+    awk -F'[./]' '{print $1"."$2"."$3"."1+$4"/"$5}' |\
+    sort -t '.' -k 1,1 -k 2,2 -k 3,3 -k 4,4 -n | tail -n1)
+
+  # Try to guess nameserver
+  NAMESERVER=$(ip -j addr show $INTERFACE | jq -r '.[0].addr_info[0].local')
+  nslookup google.com $NAMESERVER > /dev/null || {
+    NAMESERVER=$(nslookup bogusname | awk '/^Server:/{print $2}')
+    [[ ! $NAMESERVER =~ ^127 ]] && nslookup google.com $NAMESERVER > /dev/null || NAMESERVER="8.8.8.8, 1.1.1.1"
+  }
+  echo "Guessed nameserver: $NAMESERVER"
+
+  LISTENPORT=$(wg show ${INTERFACE} listen-port)
+  ENDPOINT=$(curl -s ipinfo.io | jq -r '.ip')
+
+  # Add peer
+  wg set ${INTERFACE} peer ${PUBLIC_KEY} preshared-key <(echo ${PRESHARED_KEY}) allowed-ips ${PEER_ADDRESS} || {
+    echo "Cannot add peer ${PEER_ADDRESS} with public key ${PUBLIC_KEY}"
+    exit
+  }
+  wg-quick save ${INTERFACE}
+
+  # Generate peer config
+  read -r -d$'\x01' CONFIG << END_OF_CONFIG
 [Interface]
 Address = ${PEER_ADDRESS}
 PrivateKey = ${PRIVATE_KEY}
-DNS = 8.8.8.8 (Your internal DNS server here)
+DNS = ${NAMESERVER}
 
 [Peer]
 PublicKey = ${SERVER_PUBLIC_KEY}
 PresharedKey = ${PRESHARED_KEY}
-AllowedIPs = 0.0.0.0/0
-Endpoint = example.com:443 (Your external Wireguard endpoint here)
+AllowedIPs = 0.0.0.0/1, 128.0.0.0/1
+Endpoint = ${ENDPOINT}:${LISTENPORT}
 END_OF_CONFIG
+
+  # Save added peer config
+  clientfile=$CFOLDER/$(md5sum <<<${PUBLIC_KEY}); clientfile=${clientfile%% *}
+  mkdir -p $CFOLDER
+  touch $clientfile
+  chmod go-rwx $clientfile
+  echo "$CONFIG" >${clientfile}
+
+  # Show added peer config
+  show_peer_conf ${PUBLIC_KEY}
+}
+
+# =================================================
+
+main "$@"
